<a href="https://colab.research.google.com/github/roxyconstantine-dev/Proyecto_movies/blob/main/Untitled9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tratamiento de datos
# ==============================================================================
import numpy as np
import pandas as pd
from tabulate import tabulate

# Gr√°ficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib.ticker as ticker
import seaborn as sns
import statsmodels.api as sm

# Preprocesado y modelado
# ==============================================================================
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_blobs
from sklearn.metrics import euclidean_distances
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Ridge

#from skopt.space import Real, Integer
#from skopt.utils import use_named_args
#from skopt import gp_minimize
#from skopt.plots import plot_convergence
#import optuna

# Varios
# ==============================================================================
import multiprocessing
import random
from itertools import product
#from fitter import Fitter, get_common_distributions

import matplotlib.pyplot as plt
url="https://github.com/roxyconstantine-dev/Proyecto_movies/blob/main/Peliculastest.xlsx?raw=true"
datos=pd.read_excel(url)

In [2]:
datos

,129313,Reality,no-genres-listed,no-genres-listed.1,2014,4.5,2392672,179150
0,129333,Julia,Thriller,no-genres-listed,2014.0,5.0,2582426,278632
1,129354,Focus,Crime,Drama,2015.0,5.0,2381941,256591
2,129397,Marvel One-Shot: Item 47,Fantasy,Sci-Fi,2012.0,4.5,2247732,119569
3,129428,The Second Best Exotic Marigold Hotel,Drama,no-genres-listed,2015.0,3.0,2555736,268238
4,129514,George Carlin: It's Bad for Ya!,no-genres-listed,no-genres-listed,2008.0,5.0,963207,13643
...,...,...,...,...,...,...,...,...
953,193581,Black Butler: Book of the Atlantic,Animation,Comedy,2017.0,5.0,5476944,432131
954,193583,No Game No Life: Zero,Comedy,Fantasy,2017.0,4.0,5914996,445030
955,193585,Flint,no-genres-listed,no-genres-listed,2017.0,4.0,6397426,479308
956,193587,Bungo Stray Dogs: Dead Apple,Animation,no-genres-listed,2018.0,3.0,8391976,483455
957,193609,Andrew Dice Clay: Dice Rules,no-genres-listed,no-genres-listed,1991.0,3.0,101726,37891